[tool.poetry]
name = "quiche-pantie-patch"
version = "0.1.0"
description = ""
authors = ["TenteEEEE <wander0055@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.5.1"
scikit-image = "^0.26.0"
pillow = "^12.0.0"
fastapi = "^0.139.2"
gunicorn = "^26.0.0"
uvicorn = "^0.51.0"
tqdm = "^4.69.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
